site:
  name: Asociația Christiana Cluj
  site: 'https://christianacluj.ro'
  base: '/'
  trailingSlash: false

# Default SEO metadata
metadata:
  title:
    default: Asociația Filantropică Medical-Creștină Christiana
    template: '%s — Asociația Christiana Cluj'
  description: 'Asociația Filantropică Medical-Creștină CHRISTIANA - Filiala Cluj. Construim comunitatea prin asistență medicală, socială și educațională din 1991.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Asociația Christiana Cluj
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website

i18n:
  language: ro
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/noutati/%slug%'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'noutati'
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'categorie'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'eticheta'
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'light:only'
